onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns



urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("account/", include("accounts.urls")),
    path("simpleforms/", include("simpleforms.urls")),
    path("profile/", include("profileapp.urls")), 
    path("", include("store.urls")),
    path("", include("shopping.urls")),

 ) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    
# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         path('rosetta/', include('rosetta.urls'))
#     ]

store/urls.py
from django.urls import path
from .views import home, product_detail,store,category_products,sub_category_products, help_page

urlpatterns = [
    path("",home, name="bosh-sahifa"),
    path("store/", store, name="store-page"),
    path("store/<slug:category_slug>/", category_products , name="category-products-page"),
    path("store/<slug:category_slug>/<slug:sub_category_slug>/", sub_category_products, name="subcategory-products-page"),
    path("product/<slug:slug>/", product_detail,name="product-detail"),
    path("Help/", help_page, name="help-page")
]

shopping/models.py
from django.db.models.base import Model
from store.models import Product, SubCategory
from django.db import models
from django.contrib.auth import get_user_model
from parler.models import TranslatableModel, TranslatedFields

from store.models import ProductColor, ProductSize
from accounts.models import User


def generate_cupon_code():
    import random
    import string
    

    available_chars = string.ascii_letters + string.digits
    code = ""

    for i in range(8):
        index = random.randint(0, len(available_chars)-1)
        code += available_chars[index]

    return code

def add_cupon(self):
    code = generate_cupon_code()
    cupons  = Cupon.objects.filter(code=code)


    if not cupons.exists():
        cupon = Cupon(
            code = code,
            stock = self.stock,
            expires_in = self.expires_in
        )

        cupon.save()
        for category in self.category.all():
            cupon.category.add(category)
        cupon.save()
    else:
        add_cupon(self)    

Client = get_user_model()

class Cart(models.Model):
    session_id = models.CharField(max_length=255,null=True)
    is_active = models.BooleanField(default=True)
    
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    

class CartItem(models.Model):
    color = models.ForeignKey(ProductColor, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    size = models.ForeignKey(ProductSize, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(default=1)

    reduced_price = models.FloatField(blank=True, default=0.0)
    
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)


    def total_price(self):
        if self.reduced_price != 0.0:
            return self.reduced_price * self.quantity
        else:
            return self.product.price * self.quantity
       
    def get_color_name(self):
        if self.color:
            return self.color.safe_translation_getter("name", any_language=True)
        
        return ""

    def get_size_name(self):
        if self.size:
            return self.size.safe_translation_getter("name", any_language=True)
        
        return ""

    def get_price(self):
        if self.reduced_price != 0.0:
            return self.reduced_price
        else:
            return self.product.price


class Cupon(models.Model):
    code = models.CharField(max_length=8, blank=True, unique=True)
    stock = models.FloatField()
    expires_in = models.DateTimeField()
    category = models.ManyToManyField(SubCategory)
    is_used = models.BooleanField(default=False)


    def __str__(self):
        return self.code


class CuponGroup(models.Model):
    count = models.PositiveIntegerField()
    stock = models.FloatField()
    expires_in = models.DateTimeField()
    category = models.ManyToManyField(SubCategory)

    def save(self, *args, **kwargs):
        super(CuponGroup, self).save(*args, **kwargs)
        for i in range(self.count):
            code = generate_cupon_code()
            cupons  =Cupon.objects.filter(code=code)
            if not cupons.exists():
                cupon = Cupon(
                    code = code,
                    stock = self.stock,
                    expires_in = self.expires_in
                )
                cupon.save()
                cupon_group = CuponGroup.objects.get(count=self.count, stock=self.stock,expires_in=self.expires_in)
                cupon.category.add(*cupon_group.category.all())
                cupon.save()
            else:
                add_cupon(self)    


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return self.product.title

           












    

store/models.py
from django.db import models
from datetime import datetime, timezone
from django.conf import settings
from parler.models import TranslatableModel, TranslatedFields



class Category(TranslatableModel):
    class Meta:
        verbose_name="Category"
        verbose_name_plural="Categories"

    translation = TranslatedFields(
        name = models.CharField(verbose_name="Nomi",max_length=255, null=True) 
    )

    icon=models.ImageField(upload_to="images/",null=True)
    slug = models.CharField(max_length=255,null=True)

    created_at = models.DateTimeField(verbose_name="yaratilgan sana",auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="O'zgartirilgan sana",auto_now=True)

    def __str__(self):
        return self.safe_translation_getter("name", any_language=True).__str__()
    
    def __unicode__(self):
        return self.safe_translation_getter("name", any_language=True)



class SubCategory(TranslatableModel):
    class Meta:
        verbose_name="Kichik kategoriya"
        verbose_name_plural="Kichik kategoriyalar"

    translation = TranslatedFields(
        name = models.CharField(max_length=255, null=True) 
    )
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    slug = models.CharField(max_length=255,null=True)

    def __str__(self):
        return self.safe_translation_getter("name", any_language=True).__str__()
    
    def __unicode__(self):
        return self.safe_translation_getter("name", any_language=True)

# from mptt.models import MPTTModel, TreeForeignKey


# class Kategoriya(models.Model):
#     title = models.CharField(max_length=255)
#     parent = models.ForeignKey(Kategoriya, on_delete=models.CASCADE, null=True, blank=True,                 related_name="children")

#     def __str__(self):
#         return self.title
   


# for kategoriya in kategoriyalar:
#     if not kategoriya.parent:
#         print(kategoriya)
#         for child_kategory in kategoriya.children.all():
#             print(child_kategory)

class Product(TranslatableModel):
    class Meta:
        verbose_name = "Mahsulot"
        verbose_name_plural = "Mahsulotlar"

    translation = TranslatedFields(
        title = models.CharField(max_length=255, null=True), 
        description = models.TextField(null=True)
    )

    CONDITION = {
        ("1", "yangi"),
        ("2", "ishlatilgan"),
        ("3", "bepul")
    }
    condition = models.CharField(choices=CONDITION, max_length=10, default="1", null=True)
    price = models.FloatField()
    old_price = models.FloatField(null=True)
    manufacturer = models.CharField(max_length=255, null=True)
    slug = models.CharField(max_length=255,null=True)
    rating = models.FloatField()
    guarantee = models.CharField(max_length=255, null=True, default=2)
    delivery_time = models.CharField(max_length=255, null=True)
    country = models.CharField(max_length=255, null=True)
    availabilty = models.BooleanField(default=True, null=True)
    image = models.ImageField(upload_to="images/",null=True)
    sub_category = models.ForeignKey(SubCategory,on_delete=models.CASCADE,null=True)
    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add = True, null=True)
    updated_at = models.DateTimeField(auto_now = True, null=True)


    def __str__(self):
        return self.safe_translation_getter("title", any_language=True).__str__()
    
    def __unicode__(self):
        return self.safe_translation_getter("title", any_language=True)


    def get_rating_percent(self):
        return 100 * (self.rating / 5)


    def is_new_product(self):
        time_delta = datetime.now(timezone.utc) - self.created_at
        return time_delta.seconds < 86400


        
class  ProductColor(TranslatableModel):
    translation = TranslatedFields(
        name = models.CharField(max_length=255, null=True)   
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_colors",null=True)

    def __str__(self):
        return self.safe_translation_getter("name", any_language=True).__str__()

    def __unicode__(self):
        return self.safe_translation_getter("name", any_language=True)


class ProductSize(TranslatableModel):
    translation = TranslatedFields(
        name = models.CharField(max_length=255, null=True) 
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_size",null=True)

    def __str__(self):
        return self.safe_translation_getter("name", any_language=True).__str__()

    def __unicode__(self):
        return self.safe_translation_getter("name", any_language=True)
    


class ProductImage(models.Model):
    image = models.ImageField(upload_to="images/", null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_images", null=True)
    

store/views.py
from django.shortcuts import get_object_or_404,render
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _

from .models import Category, Product, SubCategory
from .utils import filter_min_max, get_paginated, condition_filter
from shopping.models import CartItem, Cupon
from shopping.utils import get_cart




def home(request):
    products=Product.objects.filter().order_by("-rating")[:12]
 
    context={
        "products": products
    }
    return render(request,"index/index.html",context)


def search(request, products):
    word = request.GET.get('q',None)
    if word:
        return products.filter(Q(translation__title=word) | Q(translation__description=word))
    return None
    

def store(request):
    products = Product.objects.all()
    products = condition_filter(request)

    if search(request, products):
        products=search(request,products)

    paginated = get_paginated(request, products, 3)
    context = {
        "products" : paginated["items"],
        "pages": paginated["pages"],
        "word": products
        }

    return render(request, "store/store.html", context)
    

def category_products(request,category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(sub_category__category=category)
    products=filter_min_max(request,products)

    if search(request, products):
        products=search(request,products)
        
    paginated = get_paginated(request, products, 3)

    context = {
        "products" : paginated["items"],
        "pages": paginated["pages"],
        "word": products
        }
    return render(request, "store/store.html",context)
    

def sub_category_products(request,category_slug,sub_category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    subcategory = get_object_or_404(SubCategory,slug=sub_category_slug, category=category )
    products = Product.objects.filter(sub_category=subcategory)
    products=filter_min_max(request,products)

    if search(request, products):
        products=search(request,products)      
    
    paginated = get_paginated(request, products, 3)

    context = {
        "products" : paginated["items"],
        "pages": paginated["pages"],
        "word": products
        }
    return render(request, "store/store.html",context)


def product_detail(request,slug):
    products = Product.objects.filter(slug=slug)
    if not products.exists():
        return render(reverse("home-page"))
    else:
        product = products.first()

    if request.method == "POST":
        color =  request.POST.get('color',"")
        size =  request.POST.get('size',"")
        cart = get_cart(request) 

        cartitems = CartItem.objects.filter(cart=cart, product=product,color=color,size=size)

        if color == "-1" and size == "-1":
            pass
        elif cartitems.exists():
            cartitem = cartitems.first()
            cartitem.quantity += 1    
            cartitem.save()
        else:
            cartitem = CartItem(product=product, cart=cart,color=color, size=size)
            cartitem.save()
            
    context = {
        "product":product
    }
    return render(request, "store/product_detail.html", context)


def help_page(request):
    return render(request, "index/help.html")


    


    

templates/store/product_detail.html
{% extends "index/base.html" %}
{% load i18n %}
{% load change_lang %}
{% load static %}
{% block main %}


<section class="py-3 bg-light">
  <div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'bosh-sahifa' %}">{% trans 'Home' %}</a></li>
        <li class="breadcrumb-item"><a >{{product.sub_category.category}}</a></li>
        <li class="breadcrumb-item"><a >{{product.sub_category}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{product.title}}</li>
    </ol>
  </div>
</section>

<!-- ============================ ITEM DETAIL ======================== -->
<div class="row">
  <aside class="col-md-6">
    <div class="card">
      <article class="gallery-wrap">
        <div class="img-big-wrap">
          <div> <a href="#"><img src="{% get_media_prefix %}{{product.image}}" id="main-image-frame"></a></div>
        </div> <!-- slider-product.// -->
        <div class="thumbs-wrap">
          <a href="#" class="item-thumb">
            <img src="{% get_media_prefix %}{{product.image}}" class="extra-images">
          </a>
          {% for product_image in product.product_images.all %}
          <a href="#" class="item-thumb">
            <img src="{% get_media_prefix %}{{product_image.image}}" class="extra-images">
          </a>
          {% endfor %}
        </div> <!-- slider-nav.// -->
      </article> <!-- gallery-wrap .end// -->
    </div> <!-- card.// -->
  </aside>
  <main class="col-md-6">
    <article class="product-info-aside">
      <h2 class="title mt-3"> {{product.title}} </h2>

      <div class="rating-wrap my-3">
        <ul class="rating-stars">
          <li style="width:80%" class="stars-active"> 
            <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
            <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
            <i class="fa fa-star"></i> 
          </li>
          <li>
            <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
            <i class="fa fa-star"></i> <i class="fa fa-star"></i> 
            <i class="fa fa-star"></i> 
          </li>
        </ul>
        <small class="label-rating text-muted">132 reviews</small>
        <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 orders </small>
      </div> <!-- rating-wrap.// -->
      
      <div class="mb-3"> 
        <var class="price h4">USD {{product.price}}</var> 
      </div> <!-- price-detail-wrap .// -->

      <p>{{product.description}}</p>


      <input type="hidden" name="product_id" value="{{product.id}}">
      <dl class="row">
        <dt class="col-sm-3">{% trans 'Manufacturer' %}</dt>
        <dd class="col-sm-9">{{product.manufacturer}}</dd>

        {% if product.availabilty == True %}
          <dt class="col-sm-3">{% trans 'Availabilty' %}</dt>
          <dd class="col-sm-9">{% trans 'in Stock' %}</dd>
        {% else %}
          <dt class="col-sm-3">{% trans 'Availabilty' %}</dt>
          <dd class="col-sm-9">{% trans 'out of Stock' %}</dd>
        {% endif %}
          

        <dt class="col-sm-3">{% trans 'Guarantee' %}</dt>
        <dd class="col-sm-9">{{product.guarantee}} year</dd>

        <dt class="col-sm-3">Delivery time</dt>
        <dd class="col-sm-9">{{product.delivery_time}} days</dd>

        <dt class="col-sm-3">{% trans 'Size' %}</dt>
        <dd class="col-sm-9">
          <select name="size" id="id_size">
            <option value="-1" selected>{% trans 'Choose size' %}</option>
            {% for size in product.product_size.all %}
            <option value="{{size.id}}">{{size.name}}</option>
            {% endfor %}
          </select>
        </dd>


        <dt class="col-sm-3">{% trans 'Colors' %}</dt>
        <dd class="col-sm-9">
          <select name="color" id="id_color">
            <option value="-1">{% trans 'Choose color' %}</option>
            {% for color in product.product_colors.all %}
            <option value="{{color.id}}">{{color.name}}</option>
            {% endfor %}
          </select>
        </dd>
      </dl>

      <div class="form-row  mt-4">
        <div class="form-group col-md">
          <button type="submit" class="btn  btn-primary" id="add_to_cart">
            <i class="fas fa-shopping-cart"></i> <span class="text">{% trans 'Add to cart' %}</span>
          </button>
          <a href="#" class="btn btn-light">
            <i class="fas fa-envelope"></i> <span class="text">{% trans 'Contact supplier' %}</span>
          </a>
        </div> <!-- col.// -->
      </div> <!-- row.// -->

    </article> <!-- product-info-aside .// -->
  </main> <!-- col.// -->
</div> <!-- row.// -->

<!-- ================ ITEM DETAIL END .// ================= -->
{% endblock main %}


{% block script %}
<script>
  function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }
</script>
<script>
  const extraImages = document.querySelectorAll(".extra-images");
  const mainImage = document.getElementById("main-image-frame");
  extraImages.forEach((image) => {
    image.addEventListener("click", (e) => {
      e.preventDefault();
      const chosenImage = image.getAttribute("src")
      mainImage.setAttribute("src", chosenImage);
    });
  })
</script>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous">
  </script>

<script>
  var addToCart = document.getElementById("add_to_cart");
  addToCart.addEventListener("click", () => {
    console.log("Clicked");

    data = {
      product_id: "{{product.id}}",
      size: document.getElementById("id_size").value,
      color: document.getElementById("id_color").value
    }
    
    console.log(data);
    add_to_cart(data, updateCartCount);
  });

  function add_to_cart(data, callback=null) {
    const csrftoken = getCookie('csrftoken');
    fetch("{% url 'add_to_cart' %}",{
      method: "POST",
      headers: {
        "Content-type": "application/json",
        "X-CSRFToken": csrftoken
      },
      body: JSON.stringify(data)
    }).then(
      response => response.json()
    ).then((data) => {
      console.log(data);
      console.log(data.cartitems_count);
        if(callback){
          callback(data);
        }
    });
  }

  function updateCartCount(data){
    document.getElementById("id_cartitems_count").innerText = data.cartitems_count;
  }
    

</script>

{% endblock script %}

      
    

// $.ajax("http://localhost:8000/cart/add-to-cart/", {
  //   type: "GET",
  //   data: data,
  //   success: function (data, status, xhr) {
  //     console.log(data);
  //     document.getElementById("id_cartitems_count").innerText = data["cartitems_count"];
  //   }
  // });